name: app_prova
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.5
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/fundo.png
    - assets/images/header.png

  fonts:
    - family: Cartoon
      fonts:
        - asset: assets/fonts/cartoon_check/CartoonCheck-Black.ttf
